from .animal import Animal
from .beaver import Beaver
from .boa_constrictor import Boa_constrictor
from .catfish import Catfish
from .coral_snake import Coral_snake
from .cyclops_snake import Cyclops_snake
from .donkey import Donkey
from .goat import Goat
from .ibex import Ibex
from .king_cobra import King_cobra
from .llama import Llama
from .mallard import Mallard
from .nemo import Nemo
from .platypus import Platypus
from .rattle_snake import Rattlesnake
from .sheep import Sheep
from .animals_instances import bentley
from .animals_instances import bill
from .animals_instances import leif
from .animals_instances import geoffrey
from .animals_instances import carol
from .animals_instances import cheryl
from .animals_instances import maureen
from .animals_instances import prose
from .animals_instances import seth
from .animals_instances import shepherd
from .animals_instances import desmond
from .animals_instances import ingrid
from .animals_instances import noelle
from .animals_instances import ridley
from .animals_instances import keira
